# Generated by Django 5.2 on 2025-04-23 18:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0002_banner_click_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12, verbose_name='Текущий баланс')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12, verbose_name='Кредитный лимит')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='ads.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Баланс клиента',
                'verbose_name_plural': 'Балансы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер счета')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('paid', 'Оплачен'), ('canceled', 'Отменен'), ('refunded', 'Возвращен')], default='draft', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.campaign', verbose_name='Рекламная кампания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ads.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('method', models.CharField(choices=[('bank_card', 'Банковская карта'), ('yoomoney', 'ЮMoney'), ('sbp', 'СБП'), ('invoice', 'Платежное поручение')], max_length=10, verbose_name='Способ оплаты')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обработки')),
                ('external_id', models.CharField(blank=True, max_length=50, verbose_name='Внешний ID платежа')),
                ('is_refund', models.BooleanField(default=False, verbose_name='Возврат средств')),
                ('receipt_url', models.URLField(blank=True, verbose_name='Ссылка на чек')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали платежа')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='billing_inv_client__85c90b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='billing_inv_due_dat_e51895_idx'),
        ),
    ]
