# Generated by Django 5.2 on 2025-04-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='click_url',
            field=models.URLField(default='https://example.com/', verbose_name='URL для перехода по клику'),
            preserve_default=False,
        ),
    ]
