# Generated by Django 5.2 on 2025-04-21 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_company_user2client_client_campaign_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='staff',
            field=models.ManyToManyField(related_name='member_of', through='ads.User2Client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banner',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='ads.campaign'),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_clients', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='user2client',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('editor', 'Редактор'), ('reader', 'Читатель')], default='reader', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterUniqueTogether(
            name='user2client',
            unique_together={('user', 'client')},
        ),
    ]
