from pathlib import Path

CH_HOST: str
CH_PORT: int
CH_PASSWORD: str
CH_USER: str
CH_DATABASE: str
CH_SSL_CERTIFICATE_PATH: Path | None

REDIS_DATABASE: int
REDIS_PASSWORD: str
REDIS_HOST: str
REDIS_PORT: int
REDIS_SSL_CERTIFICATE_PATH: Path | None
